import type {BaseInputProps} from '../utility-types';

export type TextAreaProps = BaseInputProps<HTMLTextAreaElement> & {
    controlProps?: React.TextareaHTMLAttributes<HTMLTextAreaElement>;
    /**
     * The number of rows. If not specified, the hight will be automatically calculated based on content.
     */
    rows?: number;
    /**
     * Minimum number of rows when the hight is autogenerated.
     */
    minRows?: number;
    /**
     * Maximum number of rows when the hight is autogenerated.
     */
    maxRows?: number;
};
