name: "\U00002699 General task"
description: A defined action or activity to be done within the repository
labels: ['needs: triage']
type: Task
body:
  - type: markdown
    attributes:
      value: Thanks for your interest in the project and taking the time to fill this task!
  - type: textarea
    id: task-description
    attributes:
      label: Description
      description: Clear and detailed description of what needs to be done within the scope of the task.
      placeholder: Change code from... Move utility to... Refactor component...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the task here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/gravity-ui/uikit/issues) that pursue the same goal to avoid creating a duplicate.
          required: true
