import type {Cases} from '../../../stories/tests-factory/models';
import type {TextProps} from '../Text';

export const colorCases: Cases<TextProps['color']> = [
    'primary',
    'complementary',
    'secondary',
    'hint',
    'info',
    'info-heavy',
    'positive',
    'positive-heavy',
    'warning',
    'warning-heavy',
    'danger',
    'danger-heavy',
    'utility',
    'utility-heavy',
    'misc',
    'misc-heavy',
    'brand',
    'link',
    'link-hover',
    'link-visited',
    'link-visited-hover',
    'dark-primary',
    'dark-complementary',
    'dark-secondary',
    'light-primary',
    'light-complementary',
    'light-secondary',
    'light-hint',
    'inverted-primary',
    'inverted-complementary',
    'inverted-secondary',
    'inverted-hint',
];
export const variantCases: Cases<TextProps['variant']> = [
    'display-4',
    'display-3',
    'display-2',
    'display-1',
    'header-2',
    'header-1',
    'subheader-3',
    'subheader-2',
    'subheader-1',
    'body-3',
    'body-2',
    'body-1',
    'body-short',
    'caption-2',
    'caption-1',
    'code-3',
    'code-inline-3',
    'code-2',
    'code-inline-2',
    'code-1',
    'code-inline-1',
];
export const ellipsisCases: Cases<TextProps['ellipsis']> = [true];
export const whiteSpaceCases: Cases<TextProps['whiteSpace']> = ['nowrap', 'break-spaces'];
export const wordBreakCases: Cases<TextProps['wordBreak']> = ['break-all', 'break-word'];
