export function delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

export const emailsList = [
    'bdbrn@msn.com',
    'chlim@yahoo.ca',
    'tjensen@gmail.com',
    'morain@mac.com',
    'arachne@aol.com',
    'cfhsoft@att.net',
    'empathy@att.net',
    'goldberg@outlook.com',
    'jsnover@yahoo.ca',
    'carreras@gmail.com',
    'tubajon@att.net',
    'gbacon@gmail.com',
    'dialworld@verizon.net',
    'fglock@sbcglobal.net',
    'jane.smith@testfed.com',
    'terjesa@att.net',
    'tsuruta@optonline.net',
    'pkplex@yahoo.ca',
    'storerm@verizon.net',
    'overbom@aol.com',
    'rande@yahoo.ca',
    'crowemojo@msn.com',
    'tristan@yahoo.com',
    'ducasse@comcast.net',
    'tsuruta@mac.com',
    'kostas@mac.com',
    'rcwil@outlook.com',
    'msloan@aol.com',
    'sarahs@icloud.com',
    'srour@aol.com',
    'rnelson@me.com',
    'mcnihil@live.com',
    'treeves@me.com',
];
