import type {DOMProps, QAProps} from '../types';

export type InputControlView = 'normal' | 'clear';

export type InputControlSize = 's' | 'm' | 'l' | 'xl';

export type InputControlPin =
    | 'round-round'
    | 'brick-brick'
    | 'clear-clear'
    | 'round-brick'
    | 'brick-round'
    | 'round-clear'
    | 'clear-round'
    | 'brick-clear'
    | 'clear-brick';

export type InputControlState = 'error';

export type BaseInputControlProps<T = Element> = DOMProps &
    QAProps & {
        /**
         * Control view. Default: `'normal'`
         */
        view?: InputControlView;
        /**
         * Control size. Default: `'m'`
         */
        size?: InputControlSize;
        /**
         * Corner rounding. Default: `'round-round'`
         */
        pin?: InputControlPin;
        id?: string;
        tabIndex?: number;
        /**
         * HTML name attribute, will be autogenerated if not specified
         */
        name?: string;
        value?: string;
        defaultValue?: string;
        disabled?: boolean;
        placeholder?: string;
        /**
         * Used for managing clear button`s visibility
         */
        hasClear?: boolean;
        autoFocus?: boolean;
        autoComplete?: boolean | 'on' | 'off' | string;
        /**
         * Used for showing error state
         */
        error?: string | boolean;
        /**
         * HTML input element [type](https://devdoc.net/web/developer.mozilla.org/en-US/docs/HTML/Element/Input.html)
         */
        type?: string;
        controlRef?: React.Ref<T>;
        onUpdate?: (value: string) => void;
        onChange?: React.ChangeEventHandler<T>;
        onFocus?: React.FocusEventHandler<T>;
        onBlur?: React.FocusEventHandler<T>;
        onKeyDown?: React.KeyboardEventHandler<T>;
        onKeyUp?: React.KeyboardEventHandler<T>;
        onKeyPress?: React.KeyboardEventHandler<T>;
    };
