name: PR Preview Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: yandex-cloud/ui-preview-build-action@main
      env:
        TS_NODE_PROJECT: .storybook/tsconfig.json
