name: PR Preview Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: gravity-ui/preview-build-action@v2
        with:
          node-version: 18
