name: PR Preview Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: gravity-ui/preview-build-action@v1
      env:
        TS_NODE_PROJECT: .storybook/tsconfig.json
