name: Test Storybook

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  test_storybook:
    runs-on: ubuntu-latest
    if: github.repository == 'gravity-ui/uikit'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Tests
        run: npm run test-storybook
        env:
          TARGET_URL: https://preview.gravity-ui.com/uikit/
